# Generated by Django 2.1.5 on 2019-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190109_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
